// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epgqgnljsbwgtuwiicch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwZ3Fnbmxqc2J3Z3R1d2lpY2NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjE3MDEsImV4cCI6MjA2NTUzNzcwMX0.Xvnn3h_kvhhAgj-ech_iGcFO5Jmr0GmdWfzyLJkxm3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);